// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import controllers from "./**/*_controller.js"
import { MarksmithController, ListContinuationController } from '@avo-hq/marksmith'

controllers.forEach((controller) => {
  application.register(controller.name, controller.module.default)
})

application.register('marksmith', MarksmithController)
application.register('list-continuation', ListContinuationController)
