#!/usr/bin/env ruby

require 'English'

system("rake test:all")
@test_status = $CHILD_STATUS.exitstatus

if @test_status !=0
  puts "Tests failed"
  exit(@test_status)
end

system("bundle exec bundler-audit --update")
system("bundle exec brakeman -q -w2 --summary --no-pager")
@brakeman_status = $CHILD_STATUS.exitstatus

if @brakeman_status !=0
    puts "Brakeman found issues"
    exit(@brakeman_status)
end
