#!/usr/bin/env ruby
# frozen_string_literal: true

require 'English'
require 'rubocop'

ADDED_OR_MODIFIED = /A|AM|^M/

changed_files = `git status --porcelain`.split("\n")
                                        .grep(ADDED_OR_MODIFIED)
                                        .map do |file_name_with_status|
                                          file_name_with_status.split[1]
                                        end # rubocop:disable Style/MultilineBlockChain
                                        .select do |file_name|
                                          File.extname(file_name) == '.rb'
                                        end.join(' ')

system("rake rubocop:lint #{changed_files}") unless changed_files.empty?

exit $CHILD_STATUS.exitstatus
