AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/environments/development.rb'
    - 'config/initializers/devise.rb'
    - 'vendor/bundle/**/*'
Style/Documentation:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 25

require: rubocop-rails
