AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/environments/*'
    - 'config/initializers/devise.rb'
    - 'vendor/bundle/**/*'
Style/Documentation:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - '**/*test.rb'

require: rubocop-rails
