name: 'Deploy to my Dokku instance'

on:
  workflow_dispatch:
    branches:
    - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
  
    - name: Cancel Previous Runs # Optional step 
      uses: styfle/cancel-workflow-action@0.4.0
      with:
        access_token: ${{ github.token }}
    
    - name: Cloning repo # This step is required
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # This is required or you might get an error from Dokku

    - name: Notify Discord - Begin Build
      uses: tsickert/discord-webhook@v7.0.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
        username: CherAmi
        avatar-url: "https://i.imgur.com/lsEPYp5.png"
        content: "New push to `deploy` branch. Building site."

    - name: Push to dokku
      uses: obrassard/action-dokku-deploy@v1.0.2
      with:
        dokku_repo: 'ssh://dokku@dreambubble.xyz:22/cherami'
        ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
        deploy_branch: 'main'

    - name: Create Sentry release
      uses: getsentry/action-release@v3
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: cherami
        SENTRY_PROJECT: cherami
      with:
        environment: production

    - name: Notify Discord - Finish Build
      uses: tsickert/discord-webhook@v7.0.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
        username: CherAmi
        avatar-url: "https://i.imgur.com/lsEPYp5.png"
        content: "Deployment complete and live at [CherAmi](https://cherami.chat)!"
