name: Deploy

# yamllint disable-line rule:truthy
on:
  workflow_run:
    workflows: [Verify]
    types: [completed]
    branches: [deployment]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # third-party action that cancels previous runs
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@roleply.site:22/cardinal'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
